repository:
  name: 'facebook-cover-photo-templates'
  description: 'Facebook Cover Photo Templates (JPG & PSD)'
  homepage: 'https://www.aaronfagan.ca/blog/2015/facebook-cover-photo-templates-jpg-psd/'
  default_branch: 'master'
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: 'bug'
    color: 'CC0000'
  - name: 'feature'
    color: '336699'
  # - name: 'first-timers-only'
  #   oldname: 'Help Wanted' # Include if renaming
